version: "3.8"

services:
  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__CELERY_BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__CELERY_RESULT_BACKEND: redis://redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      PYTHONPATH: /opt/airflow/scripts:/opt/airflow/dags
    volumes:
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./airflow/dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: bash /opt/airflow/scripts/entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health"]
      interval: 10s
      retries: 5
    networks:
      - data-stack

  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    depends_on:
      airflow-webserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__CELERY_BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__CELERY_RESULT_BACKEND: redis://redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      PYTHONPATH: /opt/airflow/scripts:/opt/airflow/dags
    volumes:
      - ./logs:/opt/airflow/logs
      - ./airflow/dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    command: airflow scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $(hostname)"]
      interval: 10s
      retries: 5
    networks:
      - data-stack
  
  airflow-worker:
    build: ./airflow
    container_name: airflow-worker
    depends_on:
      airflow-webserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__CELERY_BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__CELERY_RESULT_BACKEND: redis://redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      PYTHONPATH: /opt/airflow/scripts:/opt/airflow/dags
    volumes:
      - ./logs:/opt/airflow/logs
      - ./airflow/dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    command: celery worker
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $(hostname)"]
      interval: 10s
      retries: 5
    networks:
      - data-stack

  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark/logs:/opt/bitnami/spark/logs
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f org.apache.spark.deploy.master.Master || exit 1"]
      interval: 15s
      retries: 5
    networks:
      - data-stack

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - "8082:8081"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f org.apache.spark.deploy.worker.Worker || exit 1"]
      interval: 15s
      retries: 5
    networks:
      - data-stack

  pyspark-notebook:
    image: jupyter/pyspark-notebook
    container_name: pyspark-notebook
    ports:
      - "4040:4040"
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - data-stack

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      retries: 5
    networks:
      - data-stack
    
  kafka-init-topics:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./kafka/init-topics.sh:/init-topics.sh
    entrypoint: ["sh", "/init-topics.sh"]
    networks:
      - data-stack
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8085"]
      interval: 10s
      retries: 5
    networks:
      - data-stack
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      retries: 5
    networks:
      - data-stack
  
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      retries: 5
    networks:
      - data-stack
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/ready"]
      interval: 10s
      retries: 5
    networks:
      - data-stack
  
  flower:
    image: mher/flower:latest
    container_name: flower
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USERNAME}:${FLOWER_PASSWORD}
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BROKER_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/5555' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - data-stack

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    networks:
      - data-stack

  superset:
    image: apache/superset
    container_name: superset
    environment:
      SUPERSET_ENV: dev
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    networks:
      - data-stack
  
  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx1G
    volumes:
      - ./trino/etc:/etc/trino
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 10s
      retries: 5
    networks:
      - data-stack

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
    ports:
    - "9083:9083"
    environment:
      - SERVICE_NAME=metastore
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hivepass
      - HIVE_METASTORE_DB=metastore
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=postgres
    volumes:
      - hive-metastore-data:/opt/hive/data
    command: >
      bash -c "schematool -initSchema -dbType postgres &&
               hive --service metastore"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/9083' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - data-stack

volumes:
  postgres-db-volume:
  redis-data:
  minio-data:
  hive-metastore-data:

networks:
  data-stack:
    driver: bridge